language: go

go:
  - 1.10.x

services:
  - redis-server
  - mysql

before_install:
  - go get github.com/golang/dep/...
  - go get -u golang.org/x/lint/golint
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u honnef.co/go/tools/cmd/gosimple

install:
  - $GOPATH/bin/dep ensure

before_script:
  - make keygen
  - make initdb

script:
  - make test
  - make check
