language: go

go:
  - 1.10.x

services:
  - redis-server
  - mysql

before_install:
  - go get github.com/golang/dep/...

install:
  - $GOPATH/bin/dep ensure

before_script:
  - make keygen
  - make initdb

script:
  - TEST_KEYPATH=$PWD/key/id_ecdsa make test
